### ISSUE TITLE
[PR] Building Multi-Arch Docker Images via Github Actions 

### ISSUE THREAD

**Issue by sarkrui** [iddi/oocsi-web-docker#1]
Hey Mathias, 

I found the docker image seemed to be only compatible with x86 arch, and was problematic with ARM (e.g., RPi CM4 running RPiOS 64, showed `exec format error`). I saw you indicated [here](https://github.com/iddi/oocsi/wiki/heyOOCSI!) that this docker image could be run as an Adds-on on HASS, and it did work on my VM HASS running on my x86 unRAID server, though I haven't tested with my RPi4 HASS yet. 

 I wasn't able to build Multi-arch docker image on my M1 Mac (`error: multiple platforms feature is currently not supported for docker driver.`), and I found GitHub Actions could do this job easily. Hereby I provide the validated workflow to you (Github seems doesn't allow me to PR this workflow as it's hidden). 

The built multi-arch docker image has been validated on RPiOS 64, M1 MacBook Air (12.5, Monterey), Debain 11 (on Oracle ARM). [Link:](https://hub.docker.com/repository/docker/sarkrui/oocsi-server-docker) or `docker pull sarkrui/oocsi-server-docker` for your quick test. 

_N.B. `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` need to be set in repo's **Actions secrets** (located in repoURL/settings/secrets/actions)_

```yml
name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./oocsi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: matsfunk/oocsi-server:latest

```
